matrix:
  platform:
    - linux/amd64
    - linux/arm64

platform: ${platform}

labels:
  type: exec

pipeline:
- name: publish-linux
  image: bash
  commands:
  - CODENAME=bookworm ./build.sh all $CI_COMMIT_TAG
  secrets:
  - oss_endpoint
  - oss_access_key_id
  - oss_access_key_secret
  - container_pull_secrets
  when:
    event:
    - tag
